---
name: Cascade Rebuilds

on:
  push:
    branches: [main]
    paths:
      - images/**
      - dependency-graph.yaml
      - matrix.yaml
  schedule:
    # - cron: "0 6 1 * *" # monthly, 06:00 UTC on the 1st
    - cron: 5 19 17 * *
  workflow_dispatch:
    inputs:
      roots:
        description: "Comma-separated root image names to start cascade from (optional)"
        required: false
        type: string
      full_rebuild:
        description: "Rebuild ALL images (ignore roots)"
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  plan:
    runs-on: federal
    outputs:
      subset: ${{ steps.compute.outputs.subset }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2   # or 0 for full history
      
      - name: Compute cascade subset
        id: compute
        uses: SecurityUniversalOrg/platform-actions/actions/docker-compute-cascade-subset@v1
        with:
          roots: ${{ inputs.roots }}
          full_rebuild: ${{ inputs.full_rebuild }}


  rebuild:
    needs: plan
    if: needs.plan.outputs.subset != '[]'
    runs-on: federal
    steps:
      - name: Repository dispatch via API    
        id: repo-dispatch
        uses: SecurityUniversalOrg/platform-actions/actions/docker-repo-dispatch@v1
        with:
          dispatch_token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          subset_json: ${{ needs.plan.outputs.subset }}
          repo_ns: "docker.io/securityuniversal"
